packages:
  - "apps/api"
  - "apps/web"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true

ignoreScripts: false

onlyBuiltDependencies:
  - "@boundaryml/baml"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "esbuild"
  - "prisma"
  - "protobufjs"
  - "sharp"

overrides:
  client-only: "link:apps/web/vendor/client-only"
