packages:
  - "apps/api"
  - "packages/*"

ignoreScripts: false

onlyBuiltDependencies:
  - "@boundaryml/baml"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "esbuild"
  - "prisma"
  - "protobufjs"
  - "sharp"
