/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
const fileMap = {
  
  "classifier.baml": "class Classification {\n  complexity \"low\" | \"medium\" | \"high\"\n  category \"backend\" | \"frontend\" | \"architecture\" | \"devops\" | \"coding\"\n  needsMemory bool\n  route \"haiku\" | \"sonnet\"\n}\n\nfunction ClassifyQuery(prompt: string) -> Classification {\n  client ClaudeHaiku\n  prompt #\"\n    You are an AI router for a developer reasoning engine.\n    Analyze the following user prompt and classify it.\n    \n    If the prompt is simple, factual, or requests simple code generation, set route to \"haiku\".\n    If the prompt requires complex reasoning, architecture design, or deep debugging, set route to \"sonnet\".\n    If the prompt references past context or needs architectural history, set needsMemory to true.\n\n    Prompt:\n    {{ prompt }}\n\n    Return the classification.\n  \"#\n}\n",
  "evaluator.baml": "class EvaluationResult {\n  accuracy float\n  completeness float\n  reasoning float\n  security float\n  overall float\n  needsRevision bool\n}\n\nfunction Evaluate(prompt: string, response: string) -> EvaluationResult {\n  client ClaudeHaiku\n  prompt #\"\n    Evaluate the following AI response against the user prompt.\n    Score accuracy, completeness, reasoning, and security on a scale of 0.0 to 1.0.\n    Calculate the overall score as the average of the 4 scores.\n    If the overall score is less than 0.85, set needsRevision to true.\n\n    User Prompt:\n    {{ prompt }}\n\n    AI Response:\n    {{ response }}\n\n    Provide the evaluation:\n  \"#\n}\n",
  "main.baml": "generator client {\n  output_type \"typescript\"\n  output_dir \"baml_client\"\n  version \"0.67.0\"\n}\n\nclient<llm> ClaudeHaiku {\n  provider anthropic\n  options {\n    model \"claude-3-haiku-20240307\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nclient<llm> ClaudeSonnet {\n  provider anthropic\n  options {\n    model \"claude-3-5-sonnet-20241022\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n",
  "reasoner.baml": "class Memory {\n  summary string\n  category string\n  embeddingText string\n}\n\nfunction Reason(prompt: string, memories: Memory[]) -> string {\n  client ClaudeSonnet\n  prompt #\"\n    You are the reasoning engine for Uni AI, an expert Staff Software Engineer.\n    Provide a comprehensive, accurate, and deeply reasoned answer to the user's prompt.\n    \n    {% if memories %}\n    Use the following memories for context if relevant:\n    {% for m in memories %}\n    - {{ m.summary }} ({{ m.category }}): {{ m.embeddingText }}\n    {% endfor %}\n    {% endif %}\n\n    Prompt:\n    {{ prompt }}\n    \n    Provide your expert answer:\n  \"#\n}\n",
  "writer.baml": "class MemoryEntry {\n  summary string\n  category string\n  embeddingText string\n}\n\nfunction WriteMemory(prompt: string, response: string) -> MemoryEntry {\n  client ClaudeHaiku\n  prompt #\"\n    Extract the key architectural decisions, facts, or code patterns from this interaction to store in memory.\n    The summary should be a brief label.\n    The category should be one of: backend, frontend, architecture, devops, coding.\n    The embeddingText should be a dense, factual paragraph containing all the important details to remember.\n\n    Prompt:\n    {{ prompt }}\n\n    Response:\n    {{ response }}\n\n    Extract memory:\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}